# -*- mode: conf; -*-
name: Feature Request
description: File a feature request
title: "[Feature request]: "
labels: [enhancement]
assignees:
  - 6rGKv2KGcQpF9a7pmnrxMvcmutant
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: file
    attributes:
      label: Script or program
      description: What script/program is this bug for?
      placeholder: a file name (ie get_sched_ss.py)
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is it problem related?
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
  - type: textarea
    id: solution
    attributes:
      label: Feature or solution
      description: "Describe the feature or solution you'd like"
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives
      description: |
        "Describe alternatives you've considered"
      placeholder: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      description: Additional context.
      placeholder: Add any other context or screenshots about the feature request here.
